# Generated by Django 4.2.7 on 2023-11-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=150)),
                ('desc', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='img/rooms/')),
            ],
        ),
    ]
